### ISSUE TITLE
Add https://github.com/18sg/uSHET to the list

### ISSUE THREAD

**Issue by e-larz** [Hirrolot/awesome-c-preprocessor#1]
Hi, very nice list you have there!
You may be interested in adding https://github.com/18sg/uSHET. The project heavily uses the preprocessor and there is a _very well_ documented cpp_magic.h file and the author also wrote an article about it: http://jhnet.co.uk/articles/cpp_magic

**Comment by Hirrolot** [comment]
Thanks for your suggestion!
