### ISSUE TITLE
if cxx counts as a basic compiler

### ISSUE THREAD

**Issue by retrohun** [hirrolot/awesome-c-preprocessor#8]
if cxx counts as a basic compiler, feel free to include in one of the lists:
https://github.com/retrohun/basicpp

**Comment by Hirrolot** [comment]
Hello!

This certainly counts as metaprogramming, but I'd appreciate a more detailed `README.md`. In particular, it'd be nice to have a more detailed description of how it's implemented + some example programs.

**Comment by retrohun** [comment]
> Hello!
> 
> This certainly counts as metaprogramming, but I'd appreciate a more detailed `README.md`. In particular, it'd be nice to have a more detailed description of how it's implemented + some example programs.

If Neozeed's review would be satisfactory for a testdrive, including some explanations:
https://virtuallyfun.com/wordpress/2017/09/22/basic-language-subsetdialect-c/

**Comment by hirrolot** [comment]
The character set seems to be broken in the blog post you mention:

> YES, that is correct, BASIC. Â It even has line number! Â Let’s look at a simple hello world!

I would appreciate a more detailed and proof-read post or a `README.md` document. For example, there seems to be no explanation of the terminal image in the post, so I don't even know what is this.
